# Generated by Django 5.1 on 2024-08-10 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0005_problemmodel_is_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleModel',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemBattleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.problemmodel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battlefield.battlemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionBattleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('total_runtime', models.FloatField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battlefield.battlemodel')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.problemmodel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battlefield.problembattlemodel')),
            ],
        ),
    ]
