# Generated by Django 5.1 on 2024-08-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield', '0002_usermodel_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionbattlemodel',
            old_name='b_id',
            new_name='room_id',
        ),
    ]
