# Generated by Django 5.1 on 2024-08-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield', '0004_remove_submissionbattlemodel_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionbattlemodel',
            name='testcase_passed',
            field=models.IntegerField(default=0),
        ),
    ]
