# Generated by Django 5.1 on 2024-08-11 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield', '0005_submissionbattlemodel_testcase_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionbattlemodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battlefield.usermodel'),
        ),
    ]
