# Generated by Django 5.1 on 2024-08-10 12:46

import django.db.models.deletion
import utils.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('p_id', models.CharField(default=utils.util.generateProblemId, max_length=64, primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=100)),
                ('p_content', models.TextField()),
                ('p_author', models.CharField(max_length=32)),
                ('p_likes', models.IntegerField()),
                ('p_difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_case', models.TextField()),
                ('output_case', models.TextField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.problemmodel')),
            ],
        ),
    ]
