# Generated by Django 5.1 on 2024-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
