# Generated by Django 5.1 on 2024-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_testcasemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='p_likes',
            field=models.IntegerField(default=0),
        ),
    ]
