# Generated by Django 5.1 on 2024-08-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_alter_problemmodel_p_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='is_battle',
            field=models.BooleanField(default=False),
        ),
    ]
